### ISSUE TITLE
获取不到CVE和seebug的信息

### ISSUE THREAD

**Issue by lazybootsafe** [FortuneC00kie/bug-monitor#2]
程序能正常运行，微信公众号appid appsecret 和cve_api已经添加，curl测试过https://www.saucs.com/ 此站的api，正常。
问题一 没办法获得CVE  SEEBUG消息；
连接到mongodb：
![issue](https://user-images.githubusercontent.com/9584556/38653861-5b5630c0-3e3f-11e8-9271-beaefa0bb882.png)

只有从apache获取一条数据。

问题二： 没发现推送到公众号

已经添加白名单ip ，另一第三方推送正常；

**Comment by Shadow2chery** [comment]
刚看了一下，由于seebug反爬虫代码更新了，所以程序未能获取到seebug的漏洞，导致程序阻塞了。准备重构代码，之前写的不合理，233333

**Comment by lazybootsafe** [comment]
那CVE的呢，我看过了 https://www.saucs.com/  的api 了， 还是获取不到的哦
